In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('data/BRCA_preprocessed.csv', index_col='Patient_ID')
df.head(3)
df.shape

(317, 15)

In [29]:
df.head(3)

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
Patient_ID,,,,,,,,,,,,,,,
TCGA-D8-A1XD,36.0,FEMALE,0.080353,0.42638,0.54715,0.273680,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,15-Jan-17,19-Jun-17,1
TCGA-EW-A1OX,43.0,FEMALE,-0.420320,0.57807,0.61447,-0.031505,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Apr-17,09-Nov-18,0
TCGA-A8-A079,69.0,FEMALE,0.213980,1.31140,-0.32747,-0.234260,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,08-Sep-17,09-Jun-18,1

## Example of Binary Encoding
- Manual Mapping for 2 categories

In [30]:
df['Gender'].value_counts()

Gender
FEMALE    313
MALE        4
Name: count, dtype: int64

We have 2 different classes, so we can simply replace the FEMALE by 1 and the MALE by 0, or the opposite!

In [31]:
df['Gender'] = df['Gender'].replace({'FEMALE':1, 'MALE':0})

/tmp/ipykernel_18555/1804067013.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['Gender'] = df['Gender'].replace({'FEMALE':1, 'MALE':0})

In [32]:
df.head(3)

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Tumour_Stage,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status
Patient_ID,,,,,,,,,,,,,,,
TCGA-D8-A1XD,36.0,1,0.080353,0.42638,0.54715,0.273680,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,15-Jan-17,19-Jun-17,1
TCGA-EW-A1OX,43.0,1,-0.420320,0.57807,0.61447,-0.031505,II,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Apr-17,09-Nov-18,0
TCGA-A8-A079,69.0,1,0.213980,1.31140,-0.32747,-0.234260,III,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,08-Sep-17,09-Jun-18,1

In [33]:
df["Gender"].value_counts()

Gender
1    313
0      4
Name: count, dtype: int64

## Example of One Hot Encoding using get_dummies function

In [34]:
df["Tumour_Stage"].value_counts()

Tumour_Stage
II     180
III     77
I       60
Name: count, dtype: int64

For the column "Tumour_stage" we have 3 different categories, so we should apply onehotencoding using the get_dummies function from the pandas .
This function will remove the original columns and create new columns in the end of the dataframe. We set drop_first=True, so it automatically removes the first column since with 3 categories, only 2 are enough to explain the 3 classes

In [35]:
df_encoded = pd.get_dummies(df, columns=['Tumour_Stage'], drop_first=True, dtype=int)
df_encoded.head()

,Age,Gender,Protein1,Protein2,Protein3,Protein4,Histology,ER status,PR status,HER2 status,Surgery_type,Date_of_Surgery,Date_of_Last_Visit,Patient_Status,Tumour_Stage_II,Tumour_Stage_III
Patient_ID,,,,,,,,,,,,,,,,
TCGA-D8-A1XD,36.0,1,0.080353,0.42638,0.54715,0.273680,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,15-Jan-17,19-Jun-17,1,0,1
TCGA-EW-A1OX,43.0,1,-0.420320,0.57807,0.61447,-0.031505,Mucinous Carcinoma,Positive,Positive,Negative,Lumpectomy,26-Apr-17,09-Nov-18,0,1,0
TCGA-A8-A079,69.0,1,0.213980,1.31140,-0.32747,-0.234260,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,08-Sep-17,09-Jun-18,1,0,1
TCGA-D8-A1XR,56.0,1,0.345090,-0.21147,-0.19304,0.124270,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Modified Radical Mastectomy,25-Jan-17,12-Jul-17,1,1,0
TCGA-BH-A0BF,56.0,1,0.221550,1.90680,0.52045,-0.311990,Infiltrating Ductal Carcinoma,Positive,Positive,Negative,Other,06-May-17,27-Jun-19,0,1,0

In [36]:
df_encoded["Tumour_Stage_II"].value_counts()

Tumour_Stage_II
1    180
0    137
Name: count, dtype: int64

In [37]:
df_encoded["Tumour_Stage_III"].value_counts()

Tumour_Stage_III
0    240
1     77
Name: count, dtype: int64